### ISSUE TITLE
Diyor

### ISSUE THREAD

**Issue by DiyorXasano** [Mosawer1542/Mosawerhakimi105-gmail.com#2]

**Comment by DiyorXasano** [comment]
Ты лутши

**Comment by Mosawer1542** [comment]
> Ты лутши 

https://tonhub.com/ton-connect?r={"manifestUrl":"https://tonwhales.com/ru/tonconnect-manifest.json","items":[{"name":"ton_addr"},{"name":"ton_proof","payload":"Whales"}]}&v=2&id=5862daeff68f4f5bb961e8f67a7d438096aa97bf4af2c025eec56435c611210f&ret=back&_thb=1
